// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsIosAsrApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsIosAsrApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsIosAsrApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashIosAsrApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashIosAsrApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashIosAsrApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct AsrLocaleInfo: Hashable {
  var identifier: String
  var displayName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AsrLocaleInfo? {
    let identifier = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String

    return AsrLocaleInfo(
      identifier: identifier,
      displayName: displayName
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      displayName,
    ]
  }
  static func == (lhs: AsrLocaleInfo, rhs: AsrLocaleInfo) -> Bool {
    return deepEqualsIosAsrApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosAsrApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AsrTranscriptionSegment: Hashable {
  var substring: String
  var timestamp: Double
  var duration: Double
  var confidence: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AsrTranscriptionSegment? {
    let substring = pigeonVar_list[0] as! String
    let timestamp = pigeonVar_list[1] as! Double
    let duration = pigeonVar_list[2] as! Double
    let confidence: Double? = nilOrValue(pigeonVar_list[3])

    return AsrTranscriptionSegment(
      substring: substring,
      timestamp: timestamp,
      duration: duration,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      substring,
      timestamp,
      duration,
      confidence,
    ]
  }
  static func == (lhs: AsrTranscriptionSegment, rhs: AsrTranscriptionSegment) -> Bool {
    return deepEqualsIosAsrApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosAsrApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AsrRecognitionResult: Hashable {
  var text: String
  var isFinal: Bool
  var confidence: Double? = nil
  var segments: [AsrTranscriptionSegment?]? = nil
  var speakingRate: Double? = nil
  var averagePauseDuration: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AsrRecognitionResult? {
    let text = pigeonVar_list[0] as! String
    let isFinal = pigeonVar_list[1] as! Bool
    let confidence: Double? = nilOrValue(pigeonVar_list[2])
    let segments: [AsrTranscriptionSegment?]? = nilOrValue(pigeonVar_list[3])
    let speakingRate: Double? = nilOrValue(pigeonVar_list[4])
    let averagePauseDuration: Double? = nilOrValue(pigeonVar_list[5])

    return AsrRecognitionResult(
      text: text,
      isFinal: isFinal,
      confidence: confidence,
      segments: segments,
      speakingRate: speakingRate,
      averagePauseDuration: averagePauseDuration
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isFinal,
      confidence,
      segments,
      speakingRate,
      averagePauseDuration,
    ]
  }
  static func == (lhs: AsrRecognitionResult, rhs: AsrRecognitionResult) -> Bool {
    return deepEqualsIosAsrApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosAsrApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AsrError: Hashable {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AsrError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return AsrError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: AsrError, rhs: AsrError) -> Bool {
    return deepEqualsIosAsrApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosAsrApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AsrRecognitionOptions: Hashable {
  var localeIdentifier: String? = nil
  var partialResults: Bool
  var taskHint: String? = nil
  var requiresOnDeviceRecognition: Bool
  var contextualStrings: [String?]? = nil
  var detectMultipleUtterances: Bool
  var addsPunctuation: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AsrRecognitionOptions? {
    let localeIdentifier: String? = nilOrValue(pigeonVar_list[0])
    let partialResults = pigeonVar_list[1] as! Bool
    let taskHint: String? = nilOrValue(pigeonVar_list[2])
    let requiresOnDeviceRecognition = pigeonVar_list[3] as! Bool
    let contextualStrings: [String?]? = nilOrValue(pigeonVar_list[4])
    let detectMultipleUtterances = pigeonVar_list[5] as! Bool
    let addsPunctuation = pigeonVar_list[6] as! Bool

    return AsrRecognitionOptions(
      localeIdentifier: localeIdentifier,
      partialResults: partialResults,
      taskHint: taskHint,
      requiresOnDeviceRecognition: requiresOnDeviceRecognition,
      contextualStrings: contextualStrings,
      detectMultipleUtterances: detectMultipleUtterances,
      addsPunctuation: addsPunctuation
    )
  }
  func toList() -> [Any?] {
    return [
      localeIdentifier,
      partialResults,
      taskHint,
      requiresOnDeviceRecognition,
      contextualStrings,
      detectMultipleUtterances,
      addsPunctuation,
    ]
  }
  static func == (lhs: AsrRecognitionOptions, rhs: AsrRecognitionOptions) -> Bool {
    return deepEqualsIosAsrApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosAsrApi(value: toList(), hasher: &hasher)
  }
}

private class IosAsrApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AsrLocaleInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return AsrTranscriptionSegment.fromList(self.readValue() as! [Any?])
    case 131:
      return AsrRecognitionResult.fromList(self.readValue() as! [Any?])
    case 132:
      return AsrError.fromList(self.readValue() as! [Any?])
    case 133:
      return AsrRecognitionOptions.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IosAsrApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AsrLocaleInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AsrTranscriptionSegment {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AsrRecognitionResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AsrError {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AsrRecognitionOptions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IosAsrApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IosAsrApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IosAsrApiPigeonCodecWriter(data: data)
  }
}

class IosAsrApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IosAsrApiPigeonCodec(readerWriter: IosAsrApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AsrHostApi {
  func hasPermission() throws -> Bool
  func requestPermission(completion: @escaping (Result<Bool, Error>) -> Void)
  func getAvailableLocales() throws -> [AsrLocaleInfo]
  func startListening(localeIdentifier: String?, partialResults: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func startListeningWithOptions(options: AsrRecognitionOptions, completion: @escaping (Result<Bool, Error>) -> Void)
  func recognizeAudioFile(filePath: String, options: AsrRecognitionOptions, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopListening() throws
  func cancelListening() throws
  func isOnDeviceRecognitionAvailable() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AsrHostApiSetup {
  static var codec: FlutterStandardMessageCodec { IosAsrApiPigeonCodec.shared }
  /// Sets up an instance of `AsrHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AsrHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let hasPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.hasPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasPermission()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasPermissionChannel.setMessageHandler(nil)
    }
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        api.requestPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let getAvailableLocalesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.getAvailableLocales\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAvailableLocalesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAvailableLocales()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAvailableLocalesChannel.setMessageHandler(nil)
    }
    let startListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.startListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startListeningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeIdentifierArg: String? = nilOrValue(args[0])
        let partialResultsArg = args[1] as! Bool
        api.startListening(localeIdentifier: localeIdentifierArg, partialResults: partialResultsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startListeningChannel.setMessageHandler(nil)
    }
    let startListeningWithOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.startListeningWithOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startListeningWithOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! AsrRecognitionOptions
        api.startListeningWithOptions(options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startListeningWithOptionsChannel.setMessageHandler(nil)
    }
    let recognizeAudioFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.recognizeAudioFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recognizeAudioFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let optionsArg = args[1] as! AsrRecognitionOptions
        api.recognizeAudioFile(filePath: filePathArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recognizeAudioFileChannel.setMessageHandler(nil)
    }
    let stopListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.stopListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopListeningChannel.setMessageHandler { _, reply in
        do {
          try api.stopListening()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopListeningChannel.setMessageHandler(nil)
    }
    let cancelListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.cancelListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelListeningChannel.setMessageHandler { _, reply in
        do {
          try api.cancelListening()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelListeningChannel.setMessageHandler(nil)
    }
    let isOnDeviceRecognitionAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ios_asr.AsrHostApi.isOnDeviceRecognitionAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isOnDeviceRecognitionAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isOnDeviceRecognitionAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isOnDeviceRecognitionAvailableChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AsrFlutterApiProtocol {
  func onRecognitionResult(result resultArg: AsrRecognitionResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(error errorArg: AsrError, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStatusChanged(status statusArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSoundLevelChanged(level levelArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AsrFlutterApi: AsrFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: IosAsrApiPigeonCodec {
    return IosAsrApiPigeonCodec.shared
  }
  func onRecognitionResult(result resultArg: AsrRecognitionResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ios_asr.AsrFlutterApi.onRecognitionResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onError(error errorArg: AsrError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ios_asr.AsrFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStatusChanged(status statusArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ios_asr.AsrFlutterApi.onStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSoundLevelChanged(level levelArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ios_asr.AsrFlutterApi.onSoundLevelChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([levelArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
