// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class AsrLocaleInfo {
  AsrLocaleInfo({
    required this.identifier,
    required this.displayName,
  });

  String identifier;

  String displayName;

  List<Object?> _toList() {
    return <Object?>[
      identifier,
      displayName,
    ];
  }

  Object encode() {
    return _toList();  }

  static AsrLocaleInfo decode(Object result) {
    result as List<Object?>;
    return AsrLocaleInfo(
      identifier: result[0]! as String,
      displayName: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AsrLocaleInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AsrTranscriptionSegment {
  AsrTranscriptionSegment({
    required this.substring,
    required this.timestamp,
    required this.duration,
    this.confidence,
  });

  String substring;

  double timestamp;

  double duration;

  double? confidence;

  List<Object?> _toList() {
    return <Object?>[
      substring,
      timestamp,
      duration,
      confidence,
    ];
  }

  Object encode() {
    return _toList();  }

  static AsrTranscriptionSegment decode(Object result) {
    result as List<Object?>;
    return AsrTranscriptionSegment(
      substring: result[0]! as String,
      timestamp: result[1]! as double,
      duration: result[2]! as double,
      confidence: result[3] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AsrTranscriptionSegment || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AsrRecognitionResult {
  AsrRecognitionResult({
    required this.text,
    required this.isFinal,
    this.confidence,
    this.segments,
    this.speakingRate,
    this.averagePauseDuration,
  });

  String text;

  bool isFinal;

  double? confidence;

  List<AsrTranscriptionSegment?>? segments;

  double? speakingRate;

  double? averagePauseDuration;

  List<Object?> _toList() {
    return <Object?>[
      text,
      isFinal,
      confidence,
      segments,
      speakingRate,
      averagePauseDuration,
    ];
  }

  Object encode() {
    return _toList();  }

  static AsrRecognitionResult decode(Object result) {
    result as List<Object?>;
    return AsrRecognitionResult(
      text: result[0]! as String,
      isFinal: result[1]! as bool,
      confidence: result[2] as double?,
      segments: (result[3] as List<Object?>?)?.cast<AsrTranscriptionSegment?>(),
      speakingRate: result[4] as double?,
      averagePauseDuration: result[5] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AsrRecognitionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AsrError {
  AsrError({
    required this.code,
    required this.message,
  });

  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static AsrError decode(Object result) {
    result as List<Object?>;
    return AsrError(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AsrError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AsrRecognitionOptions {
  AsrRecognitionOptions({
    this.localeIdentifier,
    this.partialResults = true,
    this.taskHint,
    this.requiresOnDeviceRecognition = false,
    this.contextualStrings,
    this.detectMultipleUtterances = false,
    this.addsPunctuation = false,
  });

  String? localeIdentifier;

  bool partialResults;

  String? taskHint;

  bool requiresOnDeviceRecognition;

  List<String?>? contextualStrings;

  bool detectMultipleUtterances;

  bool addsPunctuation;

  List<Object?> _toList() {
    return <Object?>[
      localeIdentifier,
      partialResults,
      taskHint,
      requiresOnDeviceRecognition,
      contextualStrings,
      detectMultipleUtterances,
      addsPunctuation,
    ];
  }

  Object encode() {
    return _toList();  }

  static AsrRecognitionOptions decode(Object result) {
    result as List<Object?>;
    return AsrRecognitionOptions(
      localeIdentifier: result[0] as String?,
      partialResults: result[1]! as bool,
      taskHint: result[2] as String?,
      requiresOnDeviceRecognition: result[3]! as bool,
      contextualStrings: (result[4] as List<Object?>?)?.cast<String?>(),
      detectMultipleUtterances: result[5]! as bool,
      addsPunctuation: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AsrRecognitionOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AsrLocaleInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AsrTranscriptionSegment) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is AsrRecognitionResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AsrError) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AsrRecognitionOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return AsrLocaleInfo.decode(readValue(buffer)!);
      case 130: 
        return AsrTranscriptionSegment.decode(readValue(buffer)!);
      case 131: 
        return AsrRecognitionResult.decode(readValue(buffer)!);
      case 132: 
        return AsrError.decode(readValue(buffer)!);
      case 133: 
        return AsrRecognitionOptions.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AsrHostApi {
  /// Constructor for [AsrHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AsrHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> hasPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.hasPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> requestPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<List<AsrLocaleInfo>> getAvailableLocales() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.getAvailableLocales$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<AsrLocaleInfo>();
    }
  }

  Future<bool> startListening(String? localeIdentifier, bool partialResults) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.startListening$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[localeIdentifier, partialResults]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> startListeningWithOptions(AsrRecognitionOptions options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.startListeningWithOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> recognizeAudioFile(String filePath, AsrRecognitionOptions options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.recognizeAudioFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filePath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> stopListening() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.stopListening$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelListening() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.cancelListening$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isOnDeviceRecognitionAvailable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ios_asr.AsrHostApi.isOnDeviceRecognitionAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

abstract class AsrFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onRecognitionResult(AsrRecognitionResult result);

  void onError(AsrError error);

  void onStatusChanged(String status);

  void onSoundLevelChanged(double level);

  static void setUp(AsrFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ios_asr.AsrFlutterApi.onRecognitionResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onRecognitionResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final AsrRecognitionResult? arg_result = (args[0] as AsrRecognitionResult?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onRecognitionResult was null, expected non-null AsrRecognitionResult.');
          try {
            api.onRecognitionResult(arg_result!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ios_asr.AsrFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final AsrError? arg_error = (args[0] as AsrError?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onError was null, expected non-null AsrError.');
          try {
            api.onError(arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ios_asr.AsrFlutterApi.onStatusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_status = (args[0] as String?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onStatusChanged was null, expected non-null String.');
          try {
            api.onStatusChanged(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ios_asr.AsrFlutterApi.onSoundLevelChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onSoundLevelChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_level = (args[0] as double?);
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.ios_asr.AsrFlutterApi.onSoundLevelChanged was null, expected non-null double.');
          try {
            api.onSoundLevelChanged(arg_level!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
